name: Run build.py

on:
  workflow_dispatch:

jobs:
  build_1:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run build.py
      run: python -u build.py -p arcade.db -d mame -s 0 -e 100

    - name: Upload arcade.db
      uses: actions/upload-artifact@v2
      with:
        name: arcade.db
        path: arcade.db

  build_2:
    needs: build_1
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download arcade.db
      uses: actions/download-artifact@v2
      with:
        name: arcade.db
        path: arcade_db_build/

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run build.py
      run: python -u build.py -p arcade.db -d mame -s 100 -e 200

    - name: Upload arcade.db
      uses: actions/upload-artifact@v2
      with:
        name: arcade.db
        path: arcade.db

  build_3:
    needs: build_2
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Download arcade.db
      uses: actions/download-artifact@v2
      with:
        name: arcade.db
        path: arcade_db_build/

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Run build.py
      run: python -u build.py -p arcade.db -d mame -s 200

    - name: Upload arcade.db
      uses: actions/upload-artifact@v2
      with:
        name: arcade.db
        path: arcade.db
