name: Run build.py

on:
  workflow_dispatch:

jobs:

  build0:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install

    - name: Generate timestamped filename
      run: echo "DB_FILENAME=arcade_$(date +'%Y-%m-%d-%H-%M').db" >> $GITHUB_ENV

    - name: Run build.py
      run: |
        python -u build.py -p $DB_FILENAME -d mame

    - name: Upload database
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DB_FILENAME }}
        path: ${{ env.DB_FILENAME }}
